---
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx1g
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=changeme
    volumes:
      - /docker_data/elastic-stack/elasticsearch/data:/usr/share/elasticsearch/data
      - /docker_data/elastic-stack/elasticsearch/config:/usr/share/elasticsearch/config
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - shared_bridge_1
    restart: unless-stopped
    user: "1000:1000"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1.5g

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    volumes:
      - /docker_data/elastic-stack/kibana:/usr/share/kibana/data
    ports:
      - "5601:5601"
    networks:
      - shared_bridge_1
    restart: unless-stopped
    user: "1000:1000"

networks:
  shared_bridge_1:
    external: true 