---
services:
  prometheus:
    image: docker.io/prom/prometheus:v3.2.1
    container_name: prometheus
    ports:
      - 9090:9090
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - /docker_data/config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - /docker_data/prometheus:/prometheus
    restart: unless-stopped