---
services:
  grafana:
    image: docker.io/grafana/grafana-oss:11.6.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - /docker_data/grafana:/var/lib/grafana
    restart: unless-stopped